.PHONY: android ios 
android:
	sh ../../tools/make_res.sh android ui ../../tmp/res_android
	cp ../../tmp/res_android/ui/* "../../raw/example.spritebuilder/Packages/SpriteBuilder Resources.sbpack/ccbResources/images"
ios:
	sh ../../tools/make_res.sh ios ui ../../tmp/res_ios
	cp ../../tmp/res_ios/ui/* "../../raw/example.spritebuilder/Packages/SpriteBuilder Resources.sbpack/ccbResources/images"






